packages:
    - "packages/*"
    - "apps/*"

catalog:
    # React
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3

    # TanStack Router
    "@tanstack/react-router": ^1.130.2
    "@tanstack/react-router-devtools": ^1.131.5
    "@tanstack/router-plugin": ^1.121.2
    "@tanstack/react-devtools": ^0.2.2
    "@tanstack/react-router-ssr-query": ^1.131.7
    "@tanstack/react-start": ^1.131.7

    # Build tools
    vite: ^6.3.5
    "@vitejs/plugin-react": ^4.3.4
    typescript: ^5.7.2
    tsx: ^4.19.2
    "@types/node": ^22.10.6

    # Utilities
    js-yaml: ^4.1.0
    "@types/js-yaml": ^4.0.9
    zod: ^3.24.1

    # Testing
    vitest: ^3.0.5
    "@testing-library/react": ^16.2.0
    "@testing-library/dom": ^10.4.0
    jsdom: ^26.0.0

    # Additional tools
    vite-tsconfig-paths: ^5.1.4
    "@inlang/paraglide-js": 2.2.0
    web-vitals: ^4.2.4
    tsup: ^8.0.0

    # Styling
    tailwindcss: ^4.0.6
    "@tailwindcss/vite": ^4.0.6

    # Linting and formatting
    eslint: ^9.0.0
    prettier: ^3.0.0
