// @ts-nocheck
/* eslint-disable */

export const fileHeaders = {
    generated: "// This file is generated by yaml-routes. Do not edit manually.\n",
    imports: "// Generated from routes.yml\n\n",
    standard: "// Generated by yaml-routes\n\n",
};

export const commonImports = {
    react: "import { lazy } from 'react';",
    tanstack: "import { createRootRoute, createLazyFileRoute, Outlet } from '@tanstack/react-router';",
    reactHooks: "import { useState, useEffect } from 'react';",
};

export function buildFile(sections) {
    return (
        Object.values(sections)
            .filter((section) => section && section.trim().length > 0)
            .join("\n\n") + "\n"
    );
}
