# YAML Routes Configuration for TanStack Router
# This demonstrates the yaml-routes package for TanStack Router (React Router v7 support coming soon)

# Global settings
settings:
    i18n:
        enabled: true
        defaultLocale: en
        supportedLocales: [en, es]
        # if true, locales will always be preserved in URLs, even if there is no locale path segment (recommended). If false, locale will be lost when navigating to a route without a locale segment.
        forceLocaleUrl: true
    basePath: /yaml-routes

    # Performance optimizations
    lazyComponents: true # Enable lazy loading for better code splitting (false by default)

    # TanStack Router configuration
    router:
        defaultPreload: intent # Preload strategy: 'intent' | 'render' | false
        defaultPreloadStaleTime: 30000 # 30 seconds - how long preloaded data stays fresh
        defaultGcTime: 300000 # 5 minutes - garbage collection time for unused data

# Basic routes
home:
    path: /
    component: pages/Home

getting_started:
    path: /getting-started
    component: pages/GettingStarted

advanced_examples:
    path: /advanced-examples
    component: pages/AdvancedExamples

# Route with parameters
user_profile:
    path: /user/{id}
    component: pages/UserProfile
    parameters:
        id:
            type: string
            required: true

user_images:
    path: /user/{id}/images
    component: pages/UserImages
    parameters:
        id:
            type: string
            required: true

user_image:
    path: /user/{id}/images/{imageId}
    component: pages/UserImage
    parameters:
        imageId:
            type: string
            required: true

# Internationalized routes
about:
    path:
        en: /about
        es: /acerca-de
    component: pages/About

# Route with different components per locale (Demo page)
demo:
    path:
        en: /demo
        es: /demo
    component:
        en: pages/DemoEN
        es: pages/DemoES
