# YAML Routes Configuration for TanStack Router
# This demonstrates the yaml-routes package for TanStack Router (React Router v7 support coming soon)

# Global settings
settings:
    i18n:
        enabled: true
        defaultLocale: en
        supportedLocales: [en, es]

# Basic routes
home:
    path: /
    component: pages/Home

getting_started:
    path: /getting-started
    component: pages/GettingStarted

advanced_examples:
    path: /advanced-examples
    component: pages/AdvancedExamples

# Route with parameters
user_profile:
    path: /user/{id}
    component: pages/UserProfile
    parameters:
        id:
            type: string
            required: true

user_images:
    path: /user/{id}/images
    component: pages/UserImages
    parameters:
        id:
            type: string
            required: true

user_image:
    path: /user/{id}/images/{imageId}
    component: pages/UserImage
    parameters:
        imageId:
            type: string
            required: true

# Internationalized routes
about:
    path:
        en: /about
        es: /acerca-de
    component: pages/About

# Route with different components per locale (Demo page)
demo:
    path:
        en: /demo
        es: /demo
    component:
        en: pages/DemoEN
        es: pages/DemoES
