# Enhanced routing configuration for demo app
# Global settings section for configuration
settings:
    i18n:
        enabled: true
        defaultLocale: en
        supportedLocales: [en, fr, es]
    render: ssr

# URL routes - all other sections are treated as routes
home:
    path: /
    component: pages/Home

# Route without i18n variations
neutral:
    path: /neutral-url
    component: pages/Neutral

# Route with localized paths and components
about:
    path:
        en: /about
        fr: /a-propos
        es: /acerca-de
    component: pages/About

demo:
    path:
        en: /demo
        fr: /demo
        es: /demo
    component: pages/Demo

# Special page with different components per language
special_announcement:
    path:
        en: /special-announcement
        fr: /annonce-speciale
        es: /anuncio-especial
    component:
        en: pages/SpecialAnnouncementEN
        fr: pages/SpecialAnnouncementFR
        es: pages/SpecialAnnouncementES

# User routes with parameters and localized paths
user_profile:
    path:
        en: /user/{id}
        fr: /utilisateur/{id}
        es: /usuario/{id}
    component: pages/UserProfile
    parameters:
        id:
            type: string
            required: true

user_posts:
    path:
        en: /user/{userId}/posts
        fr: /utilisateur/{userId}/articles
        es: /usuario/{userId}/publicaciones
    component: pages/UserPosts
    parameters:
        userId:
            type: string
            required: true

# Blog routes with different rendering strategy
blog_index:
    path: /blog
    component: pages/Blog
    settings:
        render: ssg

blog_post:
    path: /blog/{slug}
    component: pages/BlogPost
    parameters:
        slug:
            type: string
            required: true

# Product routes with localized paths
products:
    path:
        en: /products
        fr: /produits
        es: /productos
    component: pages/Products

product_detail:
    path:
        en: /products/{id}
        fr: /produits/{id}
        es: /productos/{id}
    component: pages/ProductDetail
    parameters:
        id:
            type: string
            required: true

product_reviews:
    path:
        en: /products/{productId}/reviews
        fr: /produits/{productId}/avis
        es: /productos/{productId}/resenas
    component: pages/ProductReviews
    parameters:
        productId:
            type: string
            required: true
