name: CI

on:
    pull_request:
        branches: [main]
    # Remove push trigger since we're building locally now

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check repository structure
              run: |
                echo "✅ Repository structure check"
                ls -la
                echo "✅ Demo app structure"
                ls -la apps/demo/
                echo "✅ Package structure"  
                ls -la packages/tanstack/
                
            - name: Check if demo is built
              run: |
                if [ -d "apps/demo/dist" ]; then
                  echo "✅ Demo is pre-built and ready for deployment"
                  ls -la apps/demo/dist/
                else
                  echo "ℹ️ Demo not built yet - will be built locally before deployment"
                fi
